### ISSUE TITLE
Implement AppLayout without AppLayout.Sidebar

### ISSUE THREAD

**Issue by nighto** [fortanix/baklava#172]
Consider the following example:

```tsx
<AppLayout>
  <AppLayout.Header>
    hello world header
  </AppLayout.Header>
  <AppLayout.Content>
    hello world content
  </AppLayout.Content>
</AppLayout>
```

That shows the content inset as if there was a sidebar defined:

![Image](https://github.com/user-attachments/assets/9bc5a1d7-b54e-4a23-a324-ce38bafdb3bf)

**Comment by mkrause** [comment]
We can fix this with `:has()` in `src/layouts/AppLayout/AppLayout.module.scss`:

```css
    display: grid;
    // Note: use `minmax(0, 1fr)` to prevent blowout: https://css-tricks.com/preventing-a-grid-blowout
    grid:
      'header' var(--bk-app-layout-header-height)
      'content' 1fr
      'footer' max-content
      / minmax(0, 1fr);
    
    &:has([slot='sidebar']) {
      grid:
        'header  header' var(--bk-app-layout-header-height)
        'sidebar content' 1fr
        'sidebar footer' max-content
        / var(--bk-app-layout-sidebar-width) minmax(0, 1fr);
    }
```
