### ISSUE TITLE
Do not inline assets (like fonts) in the `dist` output in library mode

### ISSUE THREAD

**Issue by mkrause** [fortanix/baklava#188]
We have font face definitions like:

```css
  @font-face {
    font-family: 'Source Code Pro';
    font-style: normal;
    font-weight: 400;
    src: local(''), url('@/assets/fonts/source-code-pro/source-code-pro-v14-latin-regular.woff2') format('woff2');
    font-display: block;
  }
```

By default, vite will inline these when running a (library mode) build with `npm run build`. We can add the `?no-inline` query param to prevent this. However, doing so causes some new issues in the build output, where the output paths are `../` instead of `./`.
